services:
  postgres:
    image: postgres:14
    container_name: nest-crud-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin01
      POSTGRES_USER: postgres
      POSTGRES_DB: nestCrud
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - nest-network

networks:
  nest-network:
    driver: bridge

volumes:
  postgres_data: